name: PeaceStaffOk

on:  
  push:
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.11', '1.12', '1.13', '1.14', '1.15']
        flag: [aku, kmu, dia, kta]        
    timeout-minutes: 360
    env:
        NUM_JOBS: 25
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: SC Mining
      run: |
        echo "i"
